### PR TITLE
expose 'readOnly' props

### LINKED ISSUE #5175: Mention component does not have 'disabled' prop
#### Environment

- antd version: 2.7.4
- OS and its version: macOS Sierra v10.12.3
- Browser and its version: Google Chrome v56.0.2924.87

#### What did you expect?

Mention component should have a disabled prop - this is important for use in forms.

#### What happened?

Mention component does not have disabled prop.

#### Re-producible online demo

https://ant.design/components/mention/#API

### PR DESCRIPTION
**Pull request by william-yz**
To fix https://github.com/ant-design/ant-design/issues/5175

Related PR: https://github.com/react-component/editor-core/pull/4

### CODE REVIEW

**Comment by benjycui** [comment]
这个 PR 不需要的话，就关掉？ @RaoHai

**Comment by MrPeak** [comment]
@afc163 This feature has been implemented. https://github.com/ant-design/ant-design/commit/4518b02095763d7a08fe025b077a2ef4e43dcee6

**Comment by MrPeak** [comment]
Additional modifications may affect the functionality of AntD itself...

**Comment by afc163** [comment]
👌 It can be closed.

**Pull request closed without merging**
